services:
  - type: web
    name: sgi-backend
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
